Update deploy-to-salesforce.yml 9

diff --git a/.github/workflows/deploy-to-salesforce.yml b/.github/workflows/deploy-to-salesforce.yml
--- a/.github/workflows/deploy-to-salesforce.yml
+++ b/.github/workflows/deploy-to-salesforce.yml
@@ -43,4 +43,8 @@ jobs:
 
       # Step 6: Deploy metadata to Salesforce
       - name: Deploy Salesforce Metadata
-        run: sfdx project deploy start --source-dir force-app --target-org ci-org --test-level RunLocalTests --json --verbose
+        run:  result=$(sfdx project deploy start --source-dir force-app --target-org ci-org --test-level RunLocalTests --json)   echo "$result"
+              if [[ $(echo "$result" | jq -r '.status') != "0" ]]; then
+              echo "Deployment failed."
+              exit 1
+              fi
